export const NOTE_LIST_REQUEST = 'NOTE_LIST_REQUEST'
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS'
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL'

export const NOTE_ADD_REQUEST = 'NOTE_ADD_REQUEST'
export const NOTE_ADD_SUCCESS = 'NOTE_ADD_SUCCESS'
export const NOTE_ADD_FAIL = 'NOTE_ADD_FAIL'

export const NOTE_COMPLETE_REQUEST = 'NOTE_COMPLETE_REQUEST'
export const NOTE_COMPLETE_SUCCESS = 'NOTE_COMPLETE_SUCCESS'
export const NOTE_COMPLETE_FAIL = 'NOTE_COMPLETE_FAIL'

export const NOTE_TO_DELETE_REQUEST = 'NOTE_TO_DELETE_REQUEST'
export const NOTE_TO_DELETE_SUCCESS = 'NOTE_TO_DELETE_SUCCESS'
export const NOTE_TO_DELETE_FAIL = 'NOTE_TO_DELETE_FAIL'

export const NOTE_DELETE_REQUEST = 'NOTE_DELETE_REQUEST'
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS'
export const NOTE_DELETE_FAIL = 'NOTE_DELETE_FAIL'

export const NOTE_TO_EDIT_REQUEST = 'NOTE_TO_EDIT_REQUEST'
export const NOTE_TO_EDIT_SUCCESS = 'NOTE_TO_EDIT_SUCCESS'
export const NOTE_TO_EDIT_FAIL = 'NOTE_TO_EDIT_FAIL'

export const NOTE_EDIT_REQUEST = 'NOTE_EDIT_REQUEST'
export const NOTE_EDIT_SUCCESS = 'NOTE_EDIT_SUCCESS'
export const NOTE_EDIT_FAIL = 'NOTE_EDIT_FAIL'